targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql_flutter
          scalars:
            Upload:
              type: MultipartFile
              import: 'package:http/http.dart'
