name: App Release

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: app/pubspec.yaml
          cache: true

      - name: Create .env file
        run: |
          echo "API_URL=https://api.mensa-ka.de" > .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Install dependencies
        run: flutter pub get

      - name: Run code generation
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build App Bundle (AAB)
        run: flutter build appbundle --release

      - name: Build APK
        run: flutter build apk --release

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonKey: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
          packageName: de.mensa_ka.app
          releaseFiles: app/build/app/outputs/bundle/release/app-release.aab
          track: internal
          status: completed

      - name: Upload AAB to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app/build/app/outputs/bundle/release/app-release.aab
          asset_name: app-release.aab
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload APK to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app/build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          tag: ${{ github.ref }}
          overwrite: true
